######################################################################################################
#
# Dockerfile for building "kosmtik" image , using recent LongTermSupport version ubuntu:noble
#
#  
######################################################################################################

# Move from ubuntu:noble to debian , which is more stable!
#FROM ubuntu:noble
FROM debian:bookworm

# tell that installs are made in non interactive mode
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && \
    apt install --no-install-recommends -y   ca-certificates curl gnupg unzip postgresql-client  \
    fonts-hanazono fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted  unifont \
    mapnik-utils nodejs npm  unzip git && \
    apt clean && rm -rf /var/lib/apt/lists/*  # final cleaning to save disk space

# Kosmtik installation
# Note: Ubuntu sets npm prefix to /usr/local, which breaks the install of plugins . So we must explicitely force it to /usr
#       with ubuntu:noble, the command for doing this is  "npm config set prefix /usr" 
#
# Note: which version to use ?
#  - version tagged "0.0.17"  proposed by Kosmtik README is obsolete and will fail due to troubles with some nodejs components
#  - [April2025] latest version suddenly stopped building due to changes made in March2024
#  - liam-bh had the giant idea to take the last commit that works,  here we take 5dbde8d  from Oct 14th 2024
#
# Note : Many Nodejs messages about deprecated/unsupported packages .... 
RUN npm config set prefix /usr && cd /tmp && git clone  https://github.com/kosmtik/kosmtik.git && cd /tmp/kosmtik  && git checkout 5dbde8d &&  npm install -g

# This attempt with tagged version 0.0.17 WILL NOT WORK, due to troubles with some nodejs components
# cd /tmp && git clone --branch 0.0.17 --single-branch https://github.com/example/repo.git
#RUN npm config set prefix /usr && cd /tmp/kosmtik  &&  npm install -g

# Execution of Kosmtik to install plugins
WORKDIR /usr/lib/node_modules/kosmtik/
RUN kosmtik plugins --install kosmtik-overpass-layer \
                    --install kosmtik-fetch-remote \
                    --install kosmtik-overlay \
                    --install kosmtik-open-in-josm \
                    --install kosmtik-map-compare \
                    --install kosmtik-osm-data-overlay \
                    --install kosmtik-mapnik-reference \
                    --install kosmtik-geojson-overlay
# See https://github.com/kosmtik/kosmtik/issues/302
RUN npm install -g git+https://github.com/kosmtik/kosmtik-tiles-export \
      && echo "  - kosmtik-tiles-export" >> /root/.config/kosmtik.yml \
      && cp /root/.config/kosmtik.yml /tmp/.kosmtik-config.yml

# Directory /osmhike is created by volume mapping , defined in docker-compose.yml
WORKDIR /osmhike

USER 1000

# the final executed command will be ENTRYPOINT  CMD
# but CMD will be replaced by arguments ( if there are some) of "docker-compose run myimage arguments"
# Note:  we MUST use the array format [ "xxx" , "yyy" ...] otherwise there is the risk that CMD is not taken into account
ENTRYPOINT [ "sh" , "docker/docker-startup.sh" ]
CMD  [  "kosmtik" ]
